spring.application.name=blog

jwt.secret=uxZbMKBkaojooPOxYcrprQ0Yh9nf2BgDhjENyamUS2U=

# Database Connection (this wouldn't be pushed to github in a real application, dw about it!)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect